name: "Find and Replace links"
description: "Replace web link with the another one"
inputs:
  find:
    description: "link to be replaced"
    required: true
  replace:
    description: "Final link"
    required: false
    default: ""
    

runs:
  using: "composite"
  steps:
    - name: "Escaped text in find"
      uses: thenbdev/escape-string@main
      id: escape-string-find
      with:
        text: ${{ inputs.find }}

    - name: "Debug - 1"
      shell: bash
      run: |
        echo "Debug logging here"
        git diff test/test-file.txt
        echo "Debug done"

    - name: "Escaped text in replace"
      uses: thenbdev/escape-string@main
      id: escape-string-replace
      with:
        text: ${{ inputs.replace }}

    - name: "Debug - 2"
      shell: bash
      run: |
        echo "Debug logging here"
        git diff test/test-file.txt
        echo "Debug done"

    # example.com
    - name: Just link
      uses: thenbdev/find-and-replace@main
      with:
        find: "${{ inputs.find }}"
        replace: "${{ inputs.replace }}"
        words_only: true

    - name: "Debug - 3"
      shell: bash
      run: |
        echo "Debug logging here"
        git diff test/test-file.txt
        echo "Debug done"

    # www.example.com
    - name: Link starts with www
      uses: thenbdev/find-and-replace@main
      with:
        find: "www.${{ inputs.find }}"
        replace: "www.${{ inputs.replace }}"
        words_only: true

    - name: "Debug - 4"
      shell: bash
      run: |
        echo "Debug logging here"
        git diff test/test-file.txt
        echo "Debug done"

    # (http:// or https://) example.com
    - name: Link starts with /
      uses: thenbdev/find-and-replace@main
      with:
        find: \/\([^[:space:]]*\)${{ steps.escape-string-find.outputs.text }}
        replace: \/\1${{ steps.escape-string-replace.outputs.text }}
        regex-in-find: true
        regex-in-replace: true

    # abc.example.xyz - This could be a package/library as well, not replacing

    # www.example.com/abc
    - name: Link with '/' in the end.
      uses: thenbdev/find-and-replace@main
      with:
        find: ${{ steps.escape-string-find.outputs.text }}\/
        replace: ${{ steps.escape-string-replace.outputs.text }}\/
        regex-in-find: true
        regex-in-replace: true

    - name: "Debug - 5"
      shell: bash
      run: |
        echo "Debug logging here"
        git diff test/test-file.txt
        echo "Debug done"

    # example.com?query=value
    - name: Link with query parameters
      uses: thenbdev/find-and-replace@main
      with:
        find: "${{ steps.escape-string-find.outputs.text }}?"
        replace: "${{ steps.escape-string-replace.outputs.text }}?"
        regex-in-find: true
        regex-in-replace: true
    
    - name: "Debug - 6"
      shell: bash
      run: |
        echo "Debug logging here"
        git diff test/test-file.txt
        echo "Debug done"

    # example.com#anchor_text
    - name: Link with anchors (fragment identifiers)
      uses: thenbdev/find-and-replace@main
      with:
        find: "${{ steps.escape-string-find.outputs.text }}#"
        replace: "${{ steps.escape-string-replace.outputs.text }}#"
        regex-in-find: true
        regex-in-replace: true

    - name: "Debug - 7"
      shell: bash
      run: |
        echo "Debug logging here"
        git diff test/test-file.txt
        echo "Debug done"

