name: Test web link replacement
on: 
  push:
    branches: [main]
jobs:
  test_web_link_replacement:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout customisations
        uses: actions/checkout@v3

      - id: Test
        uses: thenbdev/find-and-replace-links@main
        with: 
          find: example.com
          replace: example1.com

      - name: Restore the answers
        run: |
          git status
          git checkout HEAD -- test-answers.txt
          git status
      - name: Check if links are correctly replaced
        run: |
          cat test/test-file.txt
          git diff --exit-code test/test-file.txt test-answers.txt
      
      # Todo: add structure to test and fail the test
